# Generated by Django 5.2.8 on 2025-12-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lockapp', '0004_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='person_pics/'),
        ),
    ]
