# Generated by Django 5.2.8 on 2025-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lockapp', '0005_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='person_pics/default.jpg', null=True, upload_to='person_pics/'),
        ),
    ]
