# Generated by Django 5.2.8 on 2025-12-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lockapp', '0006_alter_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
